version: '2.29.2'

services:
  db:
    image: postgres:latest          
    environment:
      POSTGRES_USER: nemo        
      POSTGRES_PASSWORD: test 
      POSTGRES_DB: tutoring_db         
    ports:
      - "5432:5432"               
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:

